### PR TITLE
Fix: imports + doc

### PR DESCRIPTION
**Pull request by glaubinix**
Some cs fixes.

### CODE REVIEW

**Comment by glaubinix** [comment]
@rwos no idea why the nightly build fails.

**Comment by rwos** [comment]
```
PHP Fatal error:  Cannot declare class SforceSoapClient, because the name is already in use in /home/travis/build/easybiblabs/salesforce-sync/vendor/developerforce/force.com-toolkit-for-php/soapclient/SforcePartnerClient.php on line 67
```

uhm. okay. who knows. I'll try restarting but will merge otherwise

**Comment by glaubinix** [comment]
maybe add allow failure for nightly builds?

**Comment by rwos** [comment]
ja

**Pull request merged**
